import type { BeanLibraryEntry } from "./types";

export const BEAN_LIBRARY: BeanLibraryEntry[] = [
  {
    id: "ethiopia-yirgacheffe",
    name: "Ethiopia Yirgacheffe",
    origin: "Ethiopia",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Floral", "Citrus", "Berry", "Fruity"],
    description: "The birthplace of coffee. Yirgacheffe washed lots are celebrated for their tea-like clarity, jasmine florals, and bright lemon-citrus acidity.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "ethiopia-sidama-natural",
    name: "Ethiopia Sidama Natural",
    origin: "Ethiopia",
    altitude: "1700-2000m",
    processing: "Natural",
    roast: "Light",
    flavorNotes: ["Berry", "Wine-like", "Fruity", "Tropical"],
    description: "Natural-processed Sidama delivers explosive blueberry and strawberry jam flavors with a wine-like fermented sweetness.",
    typicalRatio: "1:15",
  },
  {
    id: "kenya-aa",
    name: "Kenya AA",
    origin: "Kenya",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Berry", "Citrus", "Stone Fruit", "Wine-like"],
    description: "Kenya AA is famous for its bold, blackcurrant acidity and complex stone fruit sweetness with a winey, syrupy finish.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "colombia-huila",
    name: "Colombia Huila",
    origin: "Colombia",
    altitude: "1400-1700m",
    processing: "Washed",
    roast: "Medium-Light",
    flavorNotes: ["Caramel", "Stone Fruit", "Citrus", "Chocolate"],
    description: "Huila sits in Colombia's coffee heartland. Expect well-rounded caramel sweetness, red apple acidity, and a smooth, chocolatey finish.",
    typicalRatio: "1:14–1:15",
  },
  {
    id: "brazil-cerrado",
    name: "Brazil Cerrado",
    origin: "Brazil",
    altitude: "1000-1400m",
    processing: "Natural",
    roast: "Medium",
    flavorNotes: ["Chocolate", "Nutty", "Caramel"],
    description: "Brazil's largest growing region produces reliable, low-acid naturals with deep nutty-chocolate sweetness — a classic espresso base.",
    typicalRatio: "1:13–1:14",
  },
  {
    id: "yemen-mocha",
    name: "Yemen Mocha",
    origin: "Yemen",
    altitude: "1700-2000m",
    processing: "Natural",
    roast: "Medium-Light",
    flavorNotes: ["Wine-like", "Chocolate", "Spicy", "Fruity"],
    description: "One of the world's oldest coffees. Wild-fermented naturals with complex spice, dark chocolate, and a distinctive wine-like depth.",
    typicalRatio: "1:14–1:15",
  },
  {
    id: "guatemala-antigua",
    name: "Guatemala Antigua",
    origin: "Guatemala",
    altitude: "1400-1700m",
    processing: "Washed",
    roast: "Medium",
    flavorNotes: ["Chocolate", "Caramel", "Spicy", "Nutty"],
    description: "Grown in Antigua's volcanic valleys. Well-structured with bittersweet chocolate, brown sugar, and a subtle spicy complexity.",
    typicalRatio: "1:14",
  },
  {
    id: "costa-rica-tarazu",
    name: "Costa Rica Tarrazú",
    origin: "Costa Rica",
    altitude: "1700-2000m",
    processing: "Honey",
    roast: "Medium-Light",
    flavorNotes: ["Caramel", "Stone Fruit", "Citrus", "Tropical"],
    description: "Honey-processed Tarrazú is a gateway to specialty coffee — sweet, clean, and balanced with ripe peach and golden caramel.",
    typicalRatio: "1:15",
  },
  {
    id: "panama-geisha",
    name: "Panama Geisha",
    origin: "Panama",
    altitude: "2000m+",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Floral", "Tropical", "Citrus", "Fruity"],
    description: "The world's most coveted variety. Geisha's extraordinary perfume, delicate jasmine florals, and tropical fruit complexity are unmatched.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "rwanda-bourbon",
    name: "Rwanda Bourbon",
    origin: "Rwanda",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Berry", "Floral", "Citrus", "Caramel"],
    description: "Rwanda's high-altitude Bourbon trees produce coffees of remarkable sweetness — bright red fruit, hibiscus florals, and honey-sweet finish.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "indonesia-mandheling",
    name: "Indonesia Mandheling",
    origin: "Indonesia",
    altitude: "1000-1400m",
    processing: "Wet-Hulled",
    roast: "Medium-Dark",
    flavorNotes: ["Earthy", "Chocolate", "Spicy", "Nutty"],
    description: "Classic Sumatran wet-hulled processing delivers full-bodied, earthy depth with dark chocolate and cedar spice.",
    typicalRatio: "1:13–1:14",
  },
  {
    id: "panama-anaerobic",
    name: "Panama Anaerobic Natural",
    origin: "Panama",
    altitude: "1700-2000m",
    processing: "Anaerobic",
    roast: "Light",
    flavorNotes: ["Tropical", "Wine-like", "Fruity", "Berry"],
    description: "Anaerobic fermentation amplifies Panama's already exotic flavors into a kaleidoscope of tropical fruits and fermented sweetness.",
    typicalRatio: "1:14–1:15",
  },
];
