import type { BeanLibraryEntry } from "./types";

// Extended shape used for locally-sourced Saudi roaster beans.
// Fields beyond BeanLibraryEntry (roaster, waterTemp, bloomTime, precise altitude)
// are preserved at runtime via the cast below.
type LocalBeanEntry = BeanLibraryEntry & {
  roaster?: string;
  waterTemp?: number;
};

const LOCAL_BEANS: LocalBeanEntry[] = (
  [
    {
      id: "adham-1",
      name: "أدهم",
      origin: "مزيج",
      region: "مزيج",
      altitude: "1500-2200",
      processing: "Natural",
      variety: "هجين",
      roast: "Medium",
      flavorNotes: ["Caramel", "Nutty", "Honey"],
      body: "متوسط",
      roaster: "الفارس الأسود",
      typicalRatio: "1:14",
      waterTemp: 91,
      bloomTime: 40,
      description: "مزيج خاص من الفارس الأسود. كراميل ومكسرات وعسل في كوب متوازن مريح.",
    },
    {
      id: "qoji-1",
      name: "قوجي",
      origin: "Ethiopia",
      region: "قوجي",
      altitude: "2100",
      processing: "Natural",
      variety: "Dega",
      roast: "Light",
      flavorNotes: ["Berry", "Cherry", "Grape", "Floral"],
      body: "ممتلئ",
      roaster: "دبليو",
      typicalRatio: "1:15",
      waterTemp: 90,
      bloomTime: 35,
      description: "حبوب قوجي الإثيوبية الطبيعية من دبليو. تفجّر بنكهات التوت والكرز والعنب مع لمسة زهرية.",
    },
    {
      id: "shilshili-1",
      name: "شيلشلي",
      origin: "Ethiopia",
      region: "يرغاتشيفي",
      altitude: "2000",
      processing: "Natural",
      variety: "Heirloom",
      roast: "Light",
      flavorNotes: ["Peach", "Berry", "Floral", "Honey"],
      body: "متوسط",
      roaster: "أورو",
      typicalRatio: "1:15",
      waterTemp: 94,
      bloomTime: 45,
      description: "طبيعي يرغاتشيفي من أورو. خوخ وتوت وزهور وعسل في كوب رقيق متوازن.",
    },
    {
      id: "martin-1",
      name: "مارتن",
      origin: "El Salvador",
      region: "",
      altitude: "",
      processing: "Natural",
      variety: "Red Bourbon",
      roast: "Medium",
      flavorNotes: ["Chocolate", "Hazelnut", "Walnut", "Caramel", "Strawberry"],
      body: "متوسط",
      roaster: "ممتد",
      typicalRatio: "1:14",
      waterTemp: 92,
      bloomTime: 42,
      description: "Red Bourbon سلفادوري طبيعي من ممتد. طبقات من الشوكولاتة والبندق والجوز والكراميل والفراولة.",
    },
    {
      id: "grape-honey-1",
      name: "عنب عسلي",
      origin: "Colombia",
      region: "",
      altitude: "",
      processing: "Honey",
      variety: "Castillo",
      roast: "Medium-Light",
      flavorNotes: ["Grape", "Floral", "Cacao", "Molasses"],
      body: "متوسط",
      roaster: "ممتد",
      typicalRatio: "1:14-1:15",
      waterTemp: 92,
      bloomTime: 43,
      description: "Castillo عسلي كولومبي من ممتد. عنب وزهور وكاكاو وعسل أسود في كوب عميق.",
    },
    {
      id: "hambela-1",
      name: "هامبيلا",
      origin: "Ethiopia",
      region: "أبيبا",
      altitude: "1850-2200",
      processing: "Natural",
      variety: "Heirloom",
      roast: "Light",
      flavorNotes: ["Berry", "Cherry", "Jasmine", "Honey"],
      body: "ممتلئ",
      roaster: "دبليو",
      typicalRatio: "1:15",
      waterTemp: 94,
      bloomTime: 45,
      description: "Heirloom طبيعي من أبيبا إثيوبيا من دبليو. توت وكرز وياسمين وعسل في كوب مكتمل القوام.",
    },
    {
      id: "fatima-1",
      name: "فاطمة",
      origin: "Costa Rica",
      region: "لوس سانتوس",
      altitude: "1500-1800",
      processing: "Natural",
      variety: "Catuai",
      roast: "Medium-Light",
      flavorNotes: ["Caramel", "Apple", "Berry", "Cacao", "Raisin"],
      body: "كريمي",
      roaster: "جراف",
      typicalRatio: "1:14-1:15",
      waterTemp: 92,
      bloomTime: 43,
      description: "Catuai طبيعي من لوس سانتوس من جراف. كراميل وتفاح وتوت وكاكاو وزبيب في قوام كريمي.",
    },
    {
      id: "faisal-younis-1",
      name: "فيصل يونس",
      origin: "Ethiopia",
      region: "ويست أرسي",
      altitude: "",
      processing: "Natural",
      variety: "Kurume",
      roast: "Light",
      flavorNotes: ["Fruity"],
      body: "ممتلئ",
      roaster: "عبلة",
      typicalRatio: "1:15",
      waterTemp: 94,
      bloomTime: 45,
      description: "Kurume طبيعي من ويست أرسي من عبلة. نكهات فاكهة مكثفة في كوب ممتلئ.",
    },
    {
      id: "haraz-1",
      name: "حراز",
      origin: "Yemen",
      region: "حراز",
      altitude: "1900-2500",
      processing: "Natural",
      variety: "Typica",
      roast: "Medium-Light",
      flavorNotes: ["Honey", "Nutty", "Caramel"],
      body: "ناعم وعميق",
      roaster: "جراف",
      typicalRatio: "1:14",
      waterTemp: 92,
      bloomTime: 45,
      description: "Typica يمني طبيعي من جبال حراز من جراف. عسل ومكسرات وكراميل في قوام ناعم وعميق.",
    },
    {
      id: "fruta-1",
      name: "فروتا",
      origin: "Colombia",
      region: "",
      altitude: "1400-1700m",
      processing: "Natural",
      variety: "",
      roast: "Medium",
      flavorNotes: ["Fruity", "Berry", "Tropical"],
      body: "متوسط",
      roaster: "دبليو",
      typicalRatio: "1:15",
      waterTemp: 88,
      bloomTime: 35,
      description: "كولومبيا طبيعي من دبليو. فاكهي غني بنكهات متنوعة في كوب متوازن.",
    },
    {
      id: "westvally-1",
      name: "وست فالي",
      origin: "Costa Rica",
      region: "وست فالي",
      altitude: "1400-1700m",
      processing: "Natural",
      variety: "Caturra/Catuai",
      roast: "Medium-Light",
      flavorNotes: ["Lavender", "Berry", "Fruity"],
      body: "متوسط",
      roaster: "دبليو",
      typicalRatio: "1:15",
      waterTemp: 90,
      bloomTime: 35,
      description: "وست فالي كوستاريكي طبيعي من دبليو. لافندر ورمان وتوت في كوب عطري مميز.",
    },
  ] as unknown as LocalBeanEntry[]
);

export const BEAN_LIBRARY: BeanLibraryEntry[] = [
  {
    id: "ethiopia-yirgacheffe",
    name: "Ethiopia Yirgacheffe",
    origin: "Ethiopia",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Floral", "Citrus", "Berry", "Fruity"],
    description: "مسقط رأس القهوة. تشتهر أصناف يرغاشيفي المغسولة بصفائها كالشاي وعطورها الياسمينية وحموضتها الليمونية المشرقة.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "ethiopia-sidama-natural",
    name: "Ethiopia Sidama Natural",
    origin: "Ethiopia",
    altitude: "1700-2000m",
    processing: "Natural",
    roast: "Light",
    flavorNotes: ["Berry", "Wine-like", "Fruity", "Tropical"],
    description: "تقدم سيداما المعالجة طبيعياً نكهات عنبية وفراولة مربى انفجارية مع حلاوة مخمرة كالنبيذ.",
    typicalRatio: "1:15",
  },
  {
    id: "kenya-aa",
    name: "Kenya AA",
    origin: "Kenya",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Berry", "Citrus", "Stone Fruit", "Wine-like"],
    description: "تشتهر Kenya AA بحموضتها الجريئة كالكشمش الأسود وحلاوتها المعقدة كفاكهة الحجر مع نهاية كالنبيذ والشراب.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "colombia-huila",
    name: "Colombia Huila",
    origin: "Colombia",
    altitude: "1400-1700m",
    processing: "Washed",
    roast: "Medium-Light",
    flavorNotes: ["Caramel", "Stone Fruit", "Citrus", "Chocolate"],
    description: "تقع هويلا في قلب منطقة القهوة في كولومبيا. توقع حلاوة كراميل متوازنة وحموضة تفاح أحمر ونهاية ناعمة شوكولاتية.",
    typicalRatio: "1:14–1:15",
  },
  {
    id: "brazil-cerrado",
    name: "Brazil Cerrado",
    origin: "Brazil",
    altitude: "1000-1400m",
    processing: "Natural",
    roast: "Medium",
    flavorNotes: ["Chocolate", "Nutty", "Caramel"],
    description: "أكبر مناطق إنتاج القهوة في البرازيل تنتج طبيعيات منخفضة الحموضة بحلاوة مكسرات وشوكولاتة عميقة — قاعدة Espresso الكلاسيكية.",
    typicalRatio: "1:13–1:14",
  },
  {
    id: "yemen-mocha",
    name: "Yemen Mocha",
    origin: "Yemen",
    altitude: "1700-2000m",
    processing: "Natural",
    roast: "Medium-Light",
    flavorNotes: ["Wine-like", "Chocolate", "Spicy", "Fruity"],
    description: "من أقدم القهوات في العالم. طبيعيات مخمرة برياً بتوابل معقدة وشوكولاتة داكنة وعمق كالنبيذ.",
    typicalRatio: "1:14–1:15",
  },
  {
    id: "guatemala-antigua",
    name: "Guatemala Antigua",
    origin: "Guatemala",
    altitude: "1400-1700m",
    processing: "Washed",
    roast: "Medium",
    flavorNotes: ["Chocolate", "Caramel", "Spicy", "Nutty"],
    description: "تُزرع في وديان أنتيغوا البركانية. منظمة مع شوكولاتة مرة وسكر بني وتعقيد توابل خفي.",
    typicalRatio: "1:14",
  },
  {
    id: "costa-rica-tarazu",
    name: "Costa Rica Tarrazú",
    origin: "Costa Rica",
    altitude: "1700-2000m",
    processing: "Honey",
    roast: "Medium-Light",
    flavorNotes: ["Caramel", "Stone Fruit", "Citrus", "Tropical"],
    description: "معالجة عسلية Tarrazú هي البوابة لقهوة المتخصصين — حلوة ونظيفة ومتوازنة مع خوخ ناضج وكراميل ذهبي.",
    typicalRatio: "1:15",
  },
  {
    id: "panama-geisha",
    name: "Panama Geisha",
    origin: "Panama",
    altitude: "2000m+",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Floral", "Tropical", "Citrus", "Fruity"],
    description: "الصنف الأكثر قيمة في العالم. عطر Geisha الاستثنائي وزهوره الياسمينية الرقيقة وتعقيد الفاكهة الاستوائية لا مثيل لها.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "rwanda-bourbon",
    name: "Rwanda Bourbon",
    origin: "Rwanda",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Berry", "Floral", "Citrus", "Caramel"],
    description: "تنتج أشجار Bourbon عالية الارتفاع في رواندا قهواتٍ بحلاوة مميزة — فاكهة حمراء مشرقة وزهور الكركديه ونهاية عسلية.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "indonesia-mandheling",
    name: "Indonesia Mandheling",
    origin: "Indonesia",
    altitude: "1000-1400m",
    processing: "Wet-Hulled",
    roast: "Medium-Dark",
    flavorNotes: ["Earthy", "Chocolate", "Spicy", "Nutty"],
    description: "المعالجة المقشورة الرطبة الكلاسيكية لسومطرة تمنح عمقاً ترابياً مكتمل القوام مع شوكولاتة داكنة وتوابل أرزية.",
    typicalRatio: "1:13–1:14",
  },
  {
    id: "panama-anaerobic",
    name: "Panama Anaerobic Natural",
    origin: "Panama",
    altitude: "1700-2000m",
    processing: "Anaerobic",
    roast: "Light",
    flavorNotes: ["Tropical", "Wine-like", "Fruity", "Berry"],
    description: "التخمر اللاهوائي يضخم نكهات بنما الغريبة أصلاً إلى طيف من الفواكه الاستوائية والحلاوة المخمرة.",
    typicalRatio: "1:14–1:15",
  },
  ...LOCAL_BEANS,
];
