import type { BeanLibraryEntry } from "./types";

export const BEAN_LIBRARY: BeanLibraryEntry[] = [
  {
    id: "ethiopia-yirgacheffe",
    name: "Ethiopia Yirgacheffe",
    origin: "Ethiopia",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Floral", "Citrus", "Berry", "Fruity"],
    description: "مسقط رأس القهوة. تشتهر أصناف يرغاشيفي المغسولة بصفائها كالشاي وعطورها الياسمينية وحموضتها الليمونية المشرقة.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "ethiopia-sidama-natural",
    name: "Ethiopia Sidama Natural",
    origin: "Ethiopia",
    altitude: "1700-2000m",
    processing: "Natural",
    roast: "Light",
    flavorNotes: ["Berry", "Wine-like", "Fruity", "Tropical"],
    description: "تقدم سيداما المعالجة طبيعياً نكهات عنبية وفراولة مربى انفجارية مع حلاوة مخمرة كالنبيذ.",
    typicalRatio: "1:15",
  },
  {
    id: "kenya-aa",
    name: "Kenya AA",
    origin: "Kenya",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Berry", "Citrus", "Stone Fruit", "Wine-like"],
    description: "تشتهر Kenya AA بحموضتها الجريئة كالكشمش الأسود وحلاوتها المعقدة كفاكهة الحجر مع نهاية كالنبيذ والشراب.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "colombia-huila",
    name: "Colombia Huila",
    origin: "Colombia",
    altitude: "1400-1700m",
    processing: "Washed",
    roast: "Medium-Light",
    flavorNotes: ["Caramel", "Stone Fruit", "Citrus", "Chocolate"],
    description: "تقع هويلا في قلب منطقة القهوة في كولومبيا. توقع حلاوة كراميل متوازنة وحموضة تفاح أحمر ونهاية ناعمة شوكولاتية.",
    typicalRatio: "1:14–1:15",
  },
  {
    id: "brazil-cerrado",
    name: "Brazil Cerrado",
    origin: "Brazil",
    altitude: "1000-1400m",
    processing: "Natural",
    roast: "Medium",
    flavorNotes: ["Chocolate", "Nutty", "Caramel"],
    description: "أكبر مناطق إنتاج القهوة في البرازيل تنتج طبيعيات منخفضة الحموضة بحلاوة مكسرات وشوكولاتة عميقة — قاعدة Espresso الكلاسيكية.",
    typicalRatio: "1:13–1:14",
  },
  {
    id: "yemen-mocha",
    name: "Yemen Mocha",
    origin: "Yemen",
    altitude: "1700-2000m",
    processing: "Natural",
    roast: "Medium-Light",
    flavorNotes: ["Wine-like", "Chocolate", "Spicy", "Fruity"],
    description: "من أقدم القهوات في العالم. طبيعيات مخمرة برياً بتوابل معقدة وشوكولاتة داكنة وعمق كالنبيذ.",
    typicalRatio: "1:14–1:15",
  },
  {
    id: "guatemala-antigua",
    name: "Guatemala Antigua",
    origin: "Guatemala",
    altitude: "1400-1700m",
    processing: "Washed",
    roast: "Medium",
    flavorNotes: ["Chocolate", "Caramel", "Spicy", "Nutty"],
    description: "تُزرع في وديان أنتيغوا البركانية. منظمة مع شوكولاتة مرة وسكر بني وتعقيد توابل خفي.",
    typicalRatio: "1:14",
  },
  {
    id: "costa-rica-tarazu",
    name: "Costa Rica Tarrazú",
    origin: "Costa Rica",
    altitude: "1700-2000m",
    processing: "Honey",
    roast: "Medium-Light",
    flavorNotes: ["Caramel", "Stone Fruit", "Citrus", "Tropical"],
    description: "معالجة عسلية Tarrazú هي البوابة لقهوة المتخصصين — حلوة ونظيفة ومتوازنة مع خوخ ناضج وكراميل ذهبي.",
    typicalRatio: "1:15",
  },
  {
    id: "panama-geisha",
    name: "Panama Geisha",
    origin: "Panama",
    altitude: "2000m+",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Floral", "Tropical", "Citrus", "Fruity"],
    description: "الصنف الأكثر قيمة في العالم. عطر Geisha الاستثنائي وزهوره الياسمينية الرقيقة وتعقيد الفاكهة الاستوائية لا مثيل لها.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "rwanda-bourbon",
    name: "Rwanda Bourbon",
    origin: "Rwanda",
    altitude: "1700-2000m",
    processing: "Washed",
    roast: "Light",
    flavorNotes: ["Berry", "Floral", "Citrus", "Caramel"],
    description: "تنتج أشجار Bourbon عالية الارتفاع في رواندا قهواتٍ بحلاوة مميزة — فاكهة حمراء مشرقة وزهور الكركديه ونهاية عسلية.",
    typicalRatio: "1:15–1:16",
  },
  {
    id: "indonesia-mandheling",
    name: "Indonesia Mandheling",
    origin: "Indonesia",
    altitude: "1000-1400m",
    processing: "Wet-Hulled",
    roast: "Medium-Dark",
    flavorNotes: ["Earthy", "Chocolate", "Spicy", "Nutty"],
    description: "المعالجة المقشورة الرطبة الكلاسيكية لسومطرة تمنح عمقاً ترابياً مكتمل القوام مع شوكولاتة داكنة وتوابل أرزية.",
    typicalRatio: "1:13–1:14",
  },
  {
    id: "panama-anaerobic",
    name: "Panama Anaerobic Natural",
    origin: "Panama",
    altitude: "1700-2000m",
    processing: "Anaerobic",
    roast: "Light",
    flavorNotes: ["Tropical", "Wine-like", "Fruity", "Berry"],
    description: "التخمر اللاهوائي يضخم نكهات بنما الغريبة أصلاً إلى طيف من الفواكه الاستوائية والحلاوة المخمرة.",
    typicalRatio: "1:14–1:15",
  },
];
